### ISSUE TITLE
Limitation to number of dimensions?

### ISSUE THREAD

**Issue by anonymouselephant** [stefanwalther/sense-export#13] opened 2017-01-23 09:44 UTC
Hi, I am new to your extension. Looks wonderful.
I want to use it to export data into an excel-sheet.
For that I want to use more than 10 dimensions, but after I added 10 dimensions the 'Add dimension'-button becomes grey and I am not able to add any more dimensions. To add measures is still possible.
So my question is: Is there a Limitation to the number of dimensions you can use with this Extension?

I hope this is the right place to ask.
Best regards and thanks in advance
anonymouselephant

**Comment by anonymouselephant** [comment] 2017-01-23 12:14
Okay, in the JavaScript File properties there is this code:
var dimensions = {
		uses: "dimensions",
		min: 0,
		max: 10
	};
I will probably just have to change max to a higher value

**Comment by MelissaPluke** [comment] 2017-02-13 19:46
I updated this to a higher number and it didn't seem to add any more dimensions in the extension.  Any ideas?

**Comment by anonymouselephant** [comment] 2017-02-14 14:53
Well I changed max to 20 using notepad++ and then saved the JavaScriptFile.
After that I had to reload/refresh the application pressing F5 and it worked. 
That's all I can say ;-)

**Comment by MelissaPluke** [comment] 2017-02-14 15:54
Weird.  I did the same thing and it didn't work!  I am using Qlik Sense Enterprise so I removed the whole extension from the QMC and replaced it with the updated version and it didn't work.  Thanks for the reply!

**Comment by anonymouselephant** [comment] 2017-02-14 16:22
I only changed the Extension for the desktop-version. So it is probably just an Enterprise problem.
If you can't fix it, maybe rethink if you really need more than 10 dimensions for your export. Usually you don't need that many dimensions but measures, especially if a primary key is a Dimension.

**Comment by stefanwalther** [comment] 2017-05-10 01:30
Closing as this is by design.

**Closed by stefanwalther** 2017-05-10 01:30 UTC
