### ISSUE TITLE
Export in Firefox 

### ISSUE THREAD

**Issue by edettrey** [stefanwalther/sense-export#9] opened 2016-09-09 16:35 UTC
When attempting to use this button in firefox, a "Connection lost" error is thrown
It totally locks up the application.
It will still generate the excel worksheet. 

Works fine in Chrome

Environment: 
QlikSense Server (3.0.1)
Embedded via single configurator into our flagship application. 

Any ideas?

**Comment by stefanwalther** [comment] 2017-07-20 21:57
As I cannot reproduce this issue with FireFox I am closing this issue. Please feel free to re-open if you are still experiencing the issue with the newest version of sense-export.

**Closed by stefanwalther** 2017-07-20 21:57 UTC
Labels: investigation-needed
