### ISSUE TITLE
Don't work on latest QlikSense

### ISSUE THREAD

**Issue by StanTrolav** [stefanwalther/sense-export#17] opened 2017-03-17 09:52 UTC

**Comment by stefanwalther** [comment] 2017-04-17 17:36
Can you please provide more details what's happening, thx.

**Comment by StanTrolav** [comment] 2017-04-17 19:28
Hi, Stefan. Thank's for everything that you made for Qlik.
Well... This extention just don't work in Qlik Sense server 3.

**Comment by kronkrin** [comment] 2017-05-05 11:04
Hi Stefan

Thank you for a great extension. But it stopped working in Qlik Server 3.2 SR3
Is there any chance you can help with this issue?
Thanks in advance!
Regards
Olga

**Comment by mozzak** [comment] 2017-05-08 13:24
Hi Stefan,

I can confirm. The Extension does not work in our environment anymore in 3.2.3. Button Click simply does nothing. The Chrome Debugger shows the following error:

TypeError: Cannot read property 'qUrl' of undefined

Can you please let us know if you can replicate the issue ?

thanks,
Michael

**Comment by stefanwalther** [comment] 2017-05-08 14:14
Thx for confirming, I'll have a look into it. Curious where this is coming from because the keyword "qUrl" is not used in the entire project. But I'll dig into it.

**Comment by stefanwalther** [comment] 2017-05-10 01:27
Found it, fixed with version 1.2.2 of sense-export, please give it a try.

**Closed** 2017-05-10 01:28 UTC
Labels: type:bug

**Comment by mozzak** [comment] 2017-05-10 13:06
Thanks Stefan for the quick turnaround.

It appears to work correctly now in 3.2.3 .

Out of curiousity since we have some custom extensions as well and had issues with jQuery 4 (that seems to be used now in 3.2.3). Whas this caused by api changes ir jquery 4?

thanks.

**Comment by stefanwalther** [comment] 2017-05-10 13:29
No, not at all related to jQuery, but unfortunately to an unwanted breaking change in the client code, but this will be fixed in the next version of Qlik Sense, so in general use Qlik Sense 3.2 SR3 with caution.

**Comment by mozzak** [comment] 2017-05-10 13:57
Hi Stefan,

we are about to upgrade a big client tonight to 3.2.3. Are you suggesting to hold off with the upgrade and wait for a new version ? What exactly is the issue with the client code ?

Thanks for a prompt response.

**Comment by kronkrin** [comment] 2017-05-16 08:53
Works perfect! 
Thanks a lot!

Olga

**Comment by stefanwalther** [comment] 2017-05-19 21:54
Great to hear! Thx for the feedback!
